[package]
org = "hp"
name = "Cyclesync"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.17.0"

[[dependency]]
org = "ballerina"
name = "websocket"
version = "2.14.1"

[[dependency]]
org = "ballerinax"
name = "googleapis.vision"
version = "1.6.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.16.1"

[[dependency]]
org = "ballerinax"
name = "newsapi"
version = "1.5.1"

[[dependency]]
org = "ballerinax"
name = "stripe"
version = "2.0.0"

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"