[package]
org = "hp"
name = "Cyclesync"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "googleapis.vision"
version = "1.6.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.16.1"

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"
