[container.image]
repository = "cyclesync"
name = "backend"
tag = "latest"

[container.resources]
cpu = 1.0
memory = "2Gi"

[[container.ports]]
port = 8080
protocol = "HTTP"

[[container.ports]]
port = 8094
protocol = "WS"

[[container.ports]]
port = 8097
protocol = "HTTP"

[[container.ports]]
port = 9102
protocol = "HTTP"