[settings]
buildImage = false

[container.image]
name = "cyclesync-backend"
repository = "choreo"
tag = "latest"

[[container.copy.files]]
sourceFile = "./target/bin/Cyclesync.jar"
target = "/home/ballerina/Cyclesync.jar"

[container.ports]
http = 9090
pricing = 8088
auth = 8084
notifications = 8087